package com.satan.cimchat.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table CHAT.
 */
public class Chat {

    private Long id;//聊天记录id
    private String sender;//聊天发送者账号
    private String content;//聊天消息最新内容
    private Integer newNum;//新消息条数
    private Long time;//新消息时间

    public Chat() {
    }

    public Chat(Long id) {
        this.id = id;
    }

    public Chat(Long id, String sender, String content, Integer newNum, Long time) {
        this.id = id;
        this.sender = sender;
        this.content = content;
        this.newNum = newNum;
        this.time = time;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getSender() {
        return sender;
    }

    public void setSender(String sender) {
        this.sender = sender;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public Integer getNewNum() {
        return newNum;
    }

    public void setNewNum(Integer newNum) {
        this.newNum = newNum;
    }

    public Long getTime() {
        return time;
    }

    public void setTime(Long time) {
        this.time = time;
    }

}
