package com.satan.cimchat.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.io.Serializable;

/**
 * Entity mapped to table MESSAGE.
 */
public class Message implements Serializable {

    private Long id;//消息id
    private String title;//消息标题
    private String content;//消息内容
    private String type;//消息类型
    private String sender;//消息发送者
    private String receiver;//消息接收者
    private Long time;//消息时间
    private String file;//文件
    private String fileType;//文件类型
    private Integer status;//消息状态

    public Message() {
    }

    public Message(Long id) {
        this.id = id;
    }

    public Message(Long id, String title, String content, String type, String sender, String receiver, Long time, String file, String fileType, Integer status) {
        this.id = id;
        this.title = title;
        this.content = content;
        this.type = type;
        this.sender = sender;
        this.receiver = receiver;
        this.time = time;
        this.file = file;
        this.fileType = fileType;
        this.status = status;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getSender() {
        return sender;
    }

    public void setSender(String sender) {
        this.sender = sender;
    }

    public String getReceiver() {
        return receiver;
    }

    public void setReceiver(String receiver) {
        this.receiver = receiver;
    }

    public Long getTime() {
        return time;
    }

    public void setTime(Long time) {
        this.time = time;
    }

    public String getFile() {
        return file;
    }

    public void setFile(String file) {
        this.file = file;
    }

    public String getFileType() {
        return fileType;
    }

    public void setFileType(String fileType) {
        this.fileType = fileType;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

}
